version: "3.7"

services:
  syncthing:
    container_name: syncthing-server
    image: syncthing/syncthing:latest
    ports:
      - "8384:8384"
      - "22000:22000"
    restart: always
    volumes:
      - syncthing_data:/var/syncthing

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/pool/syncthing
